config/routes.rb
Rockingsheep::Application.routes.draw do
  resources :interesteds

  root :to => 'home#index'

end

app/models/interested.rb
class Interested < ActiveRecord::Base
  attr_accessible :email_address, :ip
  validates :email_address, :presence => true, :email => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @interested = Interested.new


    flash[:notice] = ""
    if not params[:notice].nil? then
      flash[:notice] = params[:notice]
    end
    
    respond_to do |format|
      format.html
    end
  end
end

app/controllers/interesteds_controller.rb
class InterestedsController < ApplicationController
  # GET /interesteds
  # GET /interesteds.json
  def index
    @interesteds = Interested.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @interesteds }
    end
  end

  # GET /interesteds/1
  # GET /interesteds/1.json
  def show
    @interested = Interested.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @interested }
    end
  end

  # GET /interesteds/new
  # GET /interesteds/new.json
  def new
    @interested = Interested.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @interested }
    end
  end

  # GET /interesteds/1/edit
  def edit
    @interested = Interested.find(params[:id])
  end

  # POST /interesteds
  # POST /interesteds.json
  def create
    @interested = Interested.new(params[:interested])

    respond_to do |format|
      if @interested.save
        # format.html { re :template => "home/index", notice: 'Interested was successfully created.' }
        format.html { redirect_to :controller => "home", :action => "index", 
          :notice => 'Tak vi kontakter dem snarrest.' }
        # format.html { redirect_to @interested, notice: 'Interested was successfully created.' }
        format.json { render json: @interested, status: :created, location: @interested }
      else
        # format.html { render action: "new" }
        # format.html { redirect_to :controller => "home", :action => "index"}
        format.html { render :template => "home/index"}
        format.json { render json: @interested.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /interesteds/1
  # PUT /interesteds/1.json
  def update
    @interested = Interested.find(params[:id])

    respond_to do |format|
      if @interested.update_attributes(params[:interested])
        format.html { redirect_to @interested, notice: 'Interested was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @interested.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interesteds/1
  # DELETE /interesteds/1.json
  def destroy
    @interested = Interested.find(params[:id])
    @interested.destroy

    respond_to do |format|
      format.html { redirect_to interesteds_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/interesteds_helper.rb
module InterestedsHelper
end

app/views/home/index.html.erb
<div class='page-wrap'>
<%= image_tag '/images/logo.png', :class=>'logo'%>

<p>
Rokkefåret er et unikt håndlavet produkt lavet af de bedste
materialer og hådplukkede skind fra Danmark, Norge og Island.
Jeg laver dem i mit lille værksted i Ry og nyder hver gang
et nyt får er færdigt.

</p>
<p> 
Hvis du vil vide mere om rokkefåret og hvordan du får fat i det
så skriv din email addresse for neden og jeg vil kontakte dig snarreset.
</>

    

<%= form_for(@interested, :defaults => { :input_html => { :class => "getemail" } }) do |f| %>

<% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>


<% if @interested.errors.any? %>
        <div id="errorExplanation">
          <h2>Beklager der er <%= pluralize(@interested.errors.count, "fejl") %>:</h2>
          <ul>
            <% @interested.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
<% end %>
	
    <div class="noshadow">
      <%= f.label "Skriv din email her:" %><br />
      <%= f.text_field :email_address, :id=>'email_field' %>
    </div>
    <div class="actions noshadow">
      <%= f.submit "kontakt mig"%>
    </div>
<% end %>
</div>


<!-- <div id="menu">
	<h1>blah something more</h1>
	<div>&nbsp;	</div>
</div> -->

app/views/interesteds/_form.html.erb
<%= form_for(@interested) do |f| %>
  <% if @interested.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interested.errors.count, "error") %> prohibited this interested from being saved:</h2>

      <ul>
      <% @interested.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :ip %><br />
    <%= f.text_field :ip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/interesteds/edit.html.erb
<h1>Editing interested</h1>

<%= render 'form' %>

<%= link_to 'Show', @interested %> |
<%= link_to 'Back', interesteds_path %>

app/views/interesteds/index.html.erb
<h1>Listing interesteds</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Ip</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @interesteds.each do |interested| %>
  <tr>
    <td><%= interested.email %></td>
    <td><%= interested.ip %></td>
    <td><%= link_to 'Show', interested %></td>
    <td><%= link_to 'Edit', edit_interested_path(interested) %></td>
    <td><%= link_to 'Destroy', interested, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Interested', new_interested_path %>

app/views/interesteds/new.html.erb
<h1>New interested</h1>

<%= render 'form' %>

<%= link_to 'Back', interesteds_path %>

app/views/interesteds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @interested.email %>
</p>

<p>
  <b>Ip:</b>
  <%= @interested.ip %>
</p>


<%= link_to 'Edit', edit_interested_path(@interested) %> |
<%= link_to 'Back', interesteds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rockingsheep</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>